# Generated by Django 4.2.3 on 2024-05-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Content', models.TextField(max_length=2000)),
                ('photo1', models.TextField(max_length=5000)),
                ('photo2', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='clinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=50)),
                ('location', models.TextField(max_length=100)),
                ('locationLink', models.TextField(max_length=2000)),
                ('emailAddress', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('smallContent', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topContent', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='teamMemebers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('moreInfo', models.TextField(max_length=2000)),
                ('photo', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('moreInfo', models.TextField(max_length=2000)),
                ('photo', models.TextField(max_length=5000)),
                ('possitionInDesignRight', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='typeApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(default='', max_length=2000)),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='SkinApp.typeapp')),
            ],
        ),
    ]
