# Generated by Django 4.2.3 on 2024-05-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkinApp', '0002_typecategory_typeapp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeapp',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='SkinApp.typecategory'),
        ),
    ]
