# Generated by Django 4.2.3 on 2024-05-31 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkinApp', '0003_alter_typeapp_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeapp',
            name='type',
        ),
        migrations.AddField(
            model_name='typeapp',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='SkinApp.typecategory'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='SkinApp.typeapp'),
        ),
    ]
