# Generated by Django 4.2.3 on 2024-05-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinApp', '0004_remove_typeapp_type_typeapp_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeapp',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
