# Generated by Django 4.2.3 on 2024-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinApp', '0006_alter_appointment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeapp',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
